services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=book_shop
      - POSTGRES_USER=book_shop
      - POSTGRES_PASSWORD=book_password # Замініть на свій

  redis:
    image: redis:alpine

  web:
    build: .
    # ЗАМІНА: Замість runserver тепер працює Gunicorn
    command: gunicorn book_shop.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DB_HOST=db
      - DB_NAME=book_shop
      - DB_USER=book_shop
      - DB_PASSWORD=book_password
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A book_shop worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A book_shop beat -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80" # Тепер ви звертаєтесь до Nginx на 8000 порту
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: